name: github_webhook_to_pubsub
description: A Dart microservice that turns GitHub webhooks into PubSub messages.
version: 0.0.0-a1
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  github_webhooks:
    git: https://github.com/enspyrco/github_webhooks.git

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
